### ISSUE TITLE
Doesn't seem to be working

### ISSUE THREAD

**Issue by kojidev** [Valkyrie121/FPArchive#1]
Hi. You append original url to web archive, but it looks like url has to be different:
example:

Original url: https://forum.facepunch.com/f/gmoddev/nseg/Spawning-brushes-with-LUA/1/

Working archive url 
https://web.archive.org/web/20190407111707/https://forum.facepunch.com/gmoddev/nseg/Spawning-brushes-with-LUA/1/

Url generated by extension: https://web.archive.org/web/https://forum.facepunch.com/f/gmoddev/nseg/Spawning-brushes-with-LUA/1/

**Comment by voxelizedworld** [comment]
Fixed in https://github.com/Valkyrie121/FPArchive/commit/54c1014cc61e0219f388724702350b9df32c88c4
